// oxlint-disable-next-line no-unused-expressions -- The CLI evaluates this function expression.
async (page) => {
  const checks = []
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  const check = (condition, label) => { if (!condition) throw new Error(label); checks.push(label) }
  await page.goto('http://localhost:3080/basic')
  await page.evaluate(() => localStorage.removeItem('carousel-studio:project:v1'))
  await page.reload()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('heading', { level: 1 }).waitFor()
  await page.screenshot({ path: 'output/playwright/01-brand.png', fullPage: true, animations: 'disabled' })
  await page.getByLabel('Название бренда *').fill('   ')
  await page.getByRole('button', { name: 'К слайдам', exact: true }).click()
  check(await page.getByRole('alert').innerText() === 'Укажите название бренда.', 'Empty brand blocked')
  check(await page.locator('#brand').evaluate(el => document.activeElement === el), 'Invalid brand focused')
  await page.getByLabel('Название бренда *').fill('Студия редакции')
  await page.getByLabel('Контакт или подпись').fill('@editorial_studio')
  await page.getByLabel('Логотип', { exact: true }).setInputFiles('package.json')
  check((await page.getByRole('alert').innerText()).includes('PNG или JPEG'), 'Invalid logo type rejected')
  await page.getByText('Карусель', { exact: true }).screenshot({ path: 'output/playwright/test-logo.png' })
  await page.getByLabel('Логотип', { exact: true }).setInputFiles('output/playwright/test-logo.png')
  await page.getByAltText('Загруженный логотип').waitFor()
  check(await page.getByAltText('Загруженный логотип').evaluate(el => el.complete && el.naturalWidth > 0), 'Logo uploaded and decoded')
  await page.getByRole('button', { name: 'К слайдам', exact: true }).click()
  await page.getByLabel('Заголовок *', { exact: true }).fill('Чек-лист редактора: перед публикацией')
  await page.getByLabel('Текст *', { exact: true }).fill('Четыре простые проверки для сильного поста. Сохраните и используйте каждый раз.')
  await page.getByRole('button', { name: 'Редактировать слайд 4: Пункт 3', exact: true }).click()
  await page.getByLabel('Текст *', { exact: true }).fill('   ')
  await page.getByRole('button', { name: 'Редактировать слайд 1: Обложка', exact: true }).click()
  await page.getByRole('button', { name: 'К просмотру', exact: true }).click()
  check((await page.getByRole('alert').innerText()).includes('4'), 'Validation finds an empty non-active slide')
  check(await page.getByRole('button', { name: 'Редактировать слайд 4: Пункт 3', exact: true }).getAttribute('aria-pressed') === 'true', 'Invalid slide selected')
  await page.getByLabel('Текст *', { exact: true }).fill('Прочитайте текст вслух. Уберите лишние слова и исправьте опечатки.')
  await page.getByRole('button', { name: 'Редактировать слайд 1: Обложка', exact: true }).click()
  await page.reload()
  check(await page.getByLabel('Название бренда *').inputValue() === 'Студия редакции', 'Brand survives reload')
  check(await page.getByAltText('Загруженный логотип').count() === 1, 'Logo survives reload')
  await page.getByRole('button', { name: 'К слайдам', exact: true }).click()
  check(await page.getByLabel('Заголовок *', { exact: true }).inputValue() === 'Чек-лист редактора: перед публикацией', 'Edited content survives reload')
  await page.screenshot({ path: 'output/playwright/02-editor.png', fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: 'К просмотру', exact: true }).click()
  check(await page.getByRole('button', { name: 'Предыдущий слайд', exact: true }).isDisabled(), 'First slide boundary')
  const preview = page.getByRole('region', { name: /Просмотр слайдов/ })
  await preview.focus(); await page.keyboard.press('ArrowRight')
  await page.getByRole('button', { name: 'Скачать слайд 2', exact: true }).waitFor()
  check(await page.getByRole('button', { name: 'Скачать слайд 2', exact: true }).count() === 1, 'Keyboard navigation')
  for (let i = 0; i < 4; i++) await page.getByRole('button', { name: 'Следующий слайд', exact: true }).click()
  check(await page.getByRole('button', { name: 'Следующий слайд', exact: true }).isDisabled(), 'Last slide boundary')
  await preview.focus(); await page.keyboard.press('ArrowRight')
  check(await page.getByRole('button', { name: 'Скачать слайд 6', exact: true }).count() === 1, 'Keyboard stays inside slide range')
  for (let i = 0; i < 5; i++) await page.getByRole('button', { name: 'Предыдущий слайд', exact: true }).click()
  await page.screenshot({ path: 'output/playwright/03-export.png', fullPage: true, animations: 'disabled' })
  const oneDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать слайд 1', exact: true }).click()
  const png = await oneDownload
  await png.saveAs('output/playwright/exported-slide-01.png')
  check(png.suggestedFilename() === 'slide-01.png' && await png.failure() === null, 'Single PNG downloaded')
  const zipDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать ZIP', exact: true }).click()
  const zip = await zipDownload
  await zip.saveAs('output/playwright/carousel-checklist.zip')
  check(zip.suggestedFilename() === 'carousel-checklist.zip' && await zip.failure() === null, 'Full ZIP downloaded')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'output/playwright/04-mobile.png', fullPage: true, animations: 'disabled' })
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'No horizontal overflow at 390px')
  await preview.dispatchEvent('touchstart', { touches: [{ identifier: 1, clientX: 250, clientY: 100 }] })
  await preview.dispatchEvent('touchend', { changedTouches: [{ identifier: 1, clientX: 90, clientY: 100 }] })
  await page.getByRole('button', { name: 'Скачать слайд 2', exact: true }).waitFor()
  check(await page.getByRole('button', { name: 'Скачать слайд 2', exact: true }).count() === 1, 'Swipe handler changes slide')
  await page.setViewportSize({ width: 320, height: 700 })
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'No horizontal overflow at 320px')
  await page.getByRole('button', { name: 'Вернуться к текстам', exact: true }).click()
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Editor fits 320px')
  await page.getByRole('button', { name: 'Редактировать слайд 1: Обложка', exact: true }).click()
  await page.getByLabel('Заголовок *', { exact: true }).fill('Ш'.repeat(80))
  await page.getByLabel('Текст *', { exact: true }).fill('Ш'.repeat(220))
  const bottom = await page.locator('main img').evaluate(img => {
    const doc = new DOMParser().parseFromString(decodeURIComponent(img.src.split(',')[1]), 'image/svg+xml')
    const content = [...doc.querySelectorAll('text')].slice(2, 4)
    return Math.max(...content.flatMap(t => [...t.querySelectorAll('tspan')].map(s => Number(s.getAttribute('y')))))
  })
  check(bottom < 1110, 'Maximum-length text stays above footer')
  await page.getByRole('button', { name: 'Начать заново', exact: true }).click()
  await page.getByRole('button', { name: 'Отмена', exact: true }).click()
  check(await page.getByLabel('Заголовок *', { exact: true }).inputValue() === 'Ш'.repeat(80), 'Reset cancellation preserves edits')
  await page.getByRole('button', { name: 'Начать заново', exact: true }).click()
  await page.getByRole('button', { name: 'Заменить примером', exact: true }).click()
  check(await page.getByLabel('Название бренда *').inputValue() === 'Студия контента', 'Confirmed reset restores example')
  check(await page.getByAltText('Загруженный логотип').count() === 0, 'Confirmed reset clears logo')
  await page.evaluate(() => localStorage.setItem('carousel-studio:project:v1', '{broken'))
  await page.reload()
  check(await page.getByLabel('Название бренда *').inputValue() === 'Студия контента', 'Corrupt saved state recovers')
  await page.setViewportSize({ width: 1440, height: 1000 })
  check(errors.length === 0, `No browser errors: ${errors.join('; ')}`)
  return { passed: checks.length, checks }
}
