// oxlint-disable-next-line no-unused-expressions -- Evaluated by the browser CLI.
async (page) => {
 const checks=[],errors=[],check=(ok,label)=>{if(!ok)throw new Error(label);checks.push(label)}
 page.on('pageerror',e=>errors.push(e.message))
 const savedWait=()=>page.waitForFunction(()=>document.querySelector('header [role="status"]')?.textContent==='Сохранено в этом браузере')
 const saved=()=>page.evaluate(async()=>{const db=await new Promise(r=>{const q=indexedDB.open('carousel-studio');q.onsuccess=()=>r(q.result)});const get=(s,k)=>new Promise(r=>{const q=db.transaction(s).objectStore(s).get(k);q.onsuccess=()=>r(q.result)});const hydrate=async v=>v&&typeof v==='object'&&v.assetRef?get('assets',v.assetRef):Array.isArray(v)?Promise.all(v.map(hydrate)):v&&typeof v==='object'?Object.fromEntries(await Promise.all(Object.entries(v).map(async([k,x])=>[k,await hydrate(x)]))):v;const raw=await get('documents','current');const value=raw?.format==='assets-v1'?await hydrate(raw.payload):raw;db.close();return value})
 await page.getByLabel('Открыть JSON',{exact:true}).setInputFiles('output/playwright/verified-project.json')
 await page.waitForFunction(()=>document.querySelector('#group')?.options.length===3)
 await page.locator('#group').selectOption(await page.locator('#group option').last().getAttribute('value'))
 await page.getByRole('button',{name:'Свойства',exact:true}).click()
 await page.getByRole('button',{name:'Фигура',exact:true}).click();await page.getByLabel('Название слоя',{exact:true}).fill('Личный акцент')
 await savedWait()
 let original=await saved(),groupId=await page.locator('#group').inputValue(),group=original.groups.find(g=>g.id===groupId)
 const photoFixtures=await page.evaluate(()=>['#1122aa','#aa2211'].map(color=>{const c=document.createElement('canvas');c.width=1024;c.height=1024;c.getContext('2d').fillStyle=color;c.getContext('2d').fillRect(0,0,1024,1024);return c.toDataURL('image/png')}))
 let mode='valid',imageCalls=0,lastRequest
 await page.route('**/studio-api/complete',route=>{
  const b=route.request().postDataJSON();lastRequest=b
  if(b.action==='image'){imageCalls++;return route.fulfill({json:{image:photoFixtures[(imageCalls-1)%2]}})}
  if(b.action==='rewrite'||b.action==='redesign'||b.action==='retopic')return route.fulfill({json:{text:JSON.stringify({name:'Новая композиция',background:'#112233',foreground:'#ffffff',slides:b.context.slides.map((s,i)=>({title:'После запроса '+(i+1),body:'Короткий текст.',layout:'split',imagePrompt:'Новый сюжет'}))})}})
  const s=b.context.slides[0],heading=s.layers.find(e=>e.role==='heading'),shape=s.layers.find(e=>e.name==='Личный акцент')
  const operations=mode==='rename'?[{op:'rename_group',name:'Переставленная серия'},{op:'slide_order',order:b.context.slides.map(s=>s.id).reverse()}]:mode==='duplicate'?[{op:'duplicate_group',name:'Копия серии'}]:mode==='delete'?[{op:'delete_group'}]:mode==='add'?[{op:'add_slide',afterSlideId:s.id,title:'Новый кадр',body:'Текст нового кадра',layout:'poster',imageFromLayerId:s.layers.find(e=>e.type==='image').id}]:[{op:'update_layer',slideId:s.id,layerId:heading.id,patch:mode==='invalid'?{font:'MissingFont'}:{text:'Точный заголовок',fill:'#112233'}},...(mode==='valid'&&shape?[{op:'update_layer',slideId:s.id,layerId:shape.id,patch:{x:120,y:180,fill:'#8858ff'}}]:[])]
  return route.fulfill({json:{text:JSON.stringify({summary:'Обновить выбранные элементы',operations})}})
 })
 const open=async(action,scope='group')=>{await page.getByRole('link',{name:'Диалог',exact:true}).click();await page.getByLabel('Действие',{exact:true}).selectOption(action);await page.getByLabel('Контекст',{exact:true}).selectOption(scope);await page.getByLabel('Запрос',{exact:true}).fill('Измени выбранные слайды по запросу.')}
 const send=()=>page.getByRole('button',{name:'Отправить запрос',exact:true}).click()
 const apply=async(label='Применить изменения')=>{await page.getByRole('button',{name:label,exact:true}).click();if(page.url().endsWith('/chat'))await page.getByRole('link',{name:'Редактор',exact:true}).click();await savedWait();return saved()}
 await open('edit','slide');await send();await page.getByRole('button',{name:'Применить изменения',exact:true}).waitFor()
 await page.waitForFunction(()=>!Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='Применить изменения')?.disabled)
 check(JSON.stringify((await saved()).groups)===JSON.stringify(original.groups),'Request and preview leave the project unchanged')
 check(lastRequest.context.slides.length===1&&lastRequest.context.slides[0].layers.some(e=>typeof e.locked==='boolean'),'Single-slide prompt receives layer properties and precise IDs')
 await page.getByText('План сохранён',{exact:true}).waitFor();await page.reload()
 await page.getByRole('button',{name:'Применить изменения',exact:true}).waitFor()
 let edited=await apply()
 let changed=edited.groups.find(g=>g.id===groupId)
 check(changed.slides[0].title==='Точный заголовок','Prompt modifies the current slide in place')
 check(edited.groups.length===original.groups.length&&changed.id===group.id,'Editing does not append an unwanted group')
 check(JSON.stringify(changed.slides.slice(1))===JSON.stringify(group.slides.slice(1)),'Other slides remain unchanged')
 check(changed.slides[0].elements.filter(e=>e.type==='image').every(e=>group.slides[0].elements.some(x=>x.id===e.id&&x.src===e.src)),'Existing photo identities and content survive targeted edits')
 await page.getByRole('button',{name:'Отменить изменение',exact:true}).click();await savedWait();check(JSON.stringify((await saved()).groups)===JSON.stringify(original.groups),'One undo restores the complete prompt edit')
 await page.getByRole('button',{name:'Повторить изменение',exact:true}).click();await savedWait();check((await saved()).groups.find(g=>g.id===groupId).slides[0].title==='Точный заголовок','Redo restores the edit')
 await open('rewrite','slide');await send();edited=await apply('Применить новый текст');changed=edited.groups.find(g=>g.id===groupId)
 check(lastRequest.context.slides.length===1&&changed.slides[0].title==='После запроса 1','Text rewriting supports one existing slide')
 check(JSON.stringify(changed.slides.slice(1))===JSON.stringify(group.slides.slice(1))&&imageCalls===0,'Single-slide rewrite preserves surrounding slides without image purchases')
 original=edited;group=changed
 await open('redesign','group');await send();await page.getByRole('button',{name:'Заменить текущие слайды',exact:true}).waitFor()
 check(await page.getByRole('button',{name:'Заменить текущие слайды',exact:true}).isEnabled(),'Redesign can reuse all existing pictures')
 edited=await apply('Заменить текущие слайды');changed=edited.groups.find(g=>g.id===groupId)
 check(JSON.stringify(changed.slides.map(s=>s.id))===JSON.stringify(group.slides.map(s=>s.id)),'Group redesign preserves slide identities and count')
 check(changed.slides[0].elements.some(e=>e.name==='Личный акцент'),'Group redesign retains manually added graphics')
 check(imageCalls===0&&changed.slides.every(s=>s.elements.some(e=>e.type==='image')),'Group redesign retains photos without buying replacements')
 original=edited;group=changed;mode='rename'
 await open('edit','group');await send();edited=await apply();changed=edited.groups.find(g=>g.id===groupId)
 check(changed.name==='Переставленная серия'&&changed.slides[0].id===group.slides.at(-1).id,'Prompt renames and reorders the existing group')
 check(changed.slides[0].elements.some(e=>e.type==='text'&&e.role==='counter'&&e.text==='01 / 03'),'Reordered slides receive correct counters')
 mode='add';await open('edit','group');await send();edited=await apply();changed=edited.groups.find(g=>g.id===groupId)
 check(changed.slides.length===4&&changed.slides[1].title==='Новый кадр'&&changed.slides[1].elements.some(e=>e.type==='image'),'Prompt adds a slide using an existing picture')
 mode='duplicate';const groupCount=edited.groups.length;await open('edit','group');await send();edited=await apply()
 check(edited.groups.length===groupCount+1&&edited.groups.at(-1).name==='Копия серии','Prompt duplicates a group with independent identities')
 mode='delete';await open('edit','group');await send();edited=await apply();check(edited.groups.length===groupCount,'Prompt deletes the selected group after explicit application')
 await page.getByRole('button',{name:'Отменить изменение',exact:true}).click();await savedWait()
 await page.locator('#group').selectOption(groupId)
 const beforeTopic=await saved(),topicGroup=beforeTopic.groups.find(g=>g.id===groupId)
 await open('retopic','slide');await page.getByLabel('Сразу создавать изображения',{exact:true}).uncheck();await send();await page.getByRole('button',{name:'Создать изображения',exact:true}).click()
 await page.waitForFunction(()=>!Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='Заменить текущие слайды')?.disabled)
 edited=await apply('Заменить текущие слайды');changed=edited.groups.find(g=>g.id===groupId)
 check(edited.groups.length===beforeTopic.groups.length&&changed.slides.length===topicGroup.slides.length,'Retopic replaces the current slide without adding groups or slides')
 check(imageCalls===1&&changed.slides[0].elements.some(e=>e.type==='image'&&e.src!==topicGroup.slides[0].elements.find(x=>x.type==='image').src),'Retopic generates a fresh picture after plan approval')
 check(JSON.stringify(changed.slides.slice(1))===JSON.stringify(topicGroup.slides.slice(1)),'Retopic preserves every neighboring slide')
 await open('image','slide');await page.getByText('Настройки',{exact:false}).first().click();await page.locator('#model').selectOption('picture-test');await page.getByLabel('Применить изображение',{exact:true}).selectOption('replace');await send()
 await page.getByRole('button',{name:'Заменить фото на слайде',exact:true}).click();await page.getByRole('link',{name:'Редактор',exact:true}).click();await savedWait()
 const photoResult=await saved(),photoGroup=photoResult.groups.find(g=>g.id===groupId)
 check(lastRequest.references.length===1,'Photo replacement passes the original picture to a compatible model')
 const oldPhoto=changed.slides[0].elements.find(e=>e.type==='image'),newPhoto=photoGroup.slides[0].elements.find(e=>e.id===oldPhoto.id)
 check(newPhoto.src!==oldPhoto.src&&newPhoto.x===oldPhoto.x&&newPhoto.width===oldPhoto.width,'Photo replacement preserves the selected layer identity and geometry')
 await open('edit','slide');await page.getByText('Настройки',{exact:false}).first().click();await page.locator('#model').selectOption('text-test')
 mode='valid';await send();await page.getByRole('button',{name:'Применить изменения',exact:true}).waitFor()
 await page.getByRole('link',{name:'Редактор',exact:true}).click();await page.getByRole('button',{name:'Свойства',exact:true}).click();await page.getByRole('button',{name:'Заголовок',exact:true}).click();await page.getByLabel('Текст слоя',{exact:true}).fill('Ручная правка после запроса');await savedWait()
 await page.getByRole('link',{name:'Диалог',exact:true}).click()
 await page.getByText('Исходные слайды изменились. Отправьте новый запрос с текущим контекстом.',{exact:true}).waitFor()
 check(await page.getByRole('button',{name:'Применить изменения',exact:true}).isDisabled(),'A stale result cannot overwrite a newer manual edit')
 await page.getByRole('button',{name:'Убрать результат',exact:true}).click();mode='invalid';await send()
 await page.waitForFunction(()=>document.querySelector('[role="alert"]')?.textContent?.includes('Шрифт недоступен'))
 check((await saved()).groups.find(g=>g.id===groupId).slides.some(s=>s.title==='Ручная правка после запроса'),'Invalid model instructions preserve the current document')
 await page.getByRole('link',{name:'Редактор',exact:true}).click();await page.getByRole('button',{name:'Свойства',exact:true}).click();await page.getByRole('button',{name:'Заголовок',exact:true}).click();await page.getByRole('button',{name:'Подогнать текст',exact:true}).click()
 const dl=page.waitForEvent('download');await page.getByRole('button',{name:'ZIP группы',exact:true}).click();await(await dl).saveAs('output/playwright/dialog-edits.zip');check(true,'Edited group exports as ZIP')
 check(errors.length===0,'No runtime errors in prompt editing workflow')
 await page.unroute('**/studio-api/complete')
 return {passed:checks.length,checks}
}
