// oxlint-disable-next-line no-unused-expressions -- Evaluated by the browser CLI.
async (page) => {
 await page.goto('http://localhost:3080/')
 await page.waitForFunction(()=>[...document.querySelectorAll('h1')].some(e=>['Новая карусель','Редактор слайдов'].includes(e.textContent)))
 if(await page.getByRole('button',{name:'Создать проект',exact:true}).count())await page.getByRole('button',{name:'Создать проект',exact:true}).click()
 await page.getByRole('heading',{name:'Редактор слайдов',exact:true}).waitFor()
 await page.getByLabel('Открыть JSON',{exact:true}).setInputFiles('output/playwright/production-project.json')
 await page.waitForFunction(()=>document.querySelectorAll('#group option').length===2)
 await page.waitForFunction(()=>document.querySelector('#group option:last-child')?.textContent.startsWith('FORM.'))
 await page.locator('#group').selectOption(await page.locator('#group option').last().getAttribute('value'))
 await page.waitForFunction(()=>document.querySelectorAll('button[aria-label^="Открыть слайд"]').length===4)
 await page.setViewportSize({width:1600,height:1100})
 await page.getByRole('tab',{name:'Дизайн',exact:true}).click()
 await page.getByRole('tab',{name:'Свойства',exact:true}).click()
 await page.waitForFunction(()=>{const images=[...document.querySelectorAll('button[aria-label^="Открыть слайд"] img')];return images.length===4&&images.every(e=>e.complete&&e.naturalWidth>0)})
 await page.waitForFunction(()=>document.querySelector('header [role="status"]')?.textContent==='Сохранено в этом браузере')
 await page.waitForFunction(()=>document.getAnimations().every(a=>a.playState!=='running'))
 await page.screenshot({path:'docs/screenshots/editor.png',fullPage:true})
 await page.getByRole('button',{name:'Заголовок',exact:true}).click()
 await page.waitForFunction(()=>document.getAnimations().every(a=>a.playState!=='running'))
 await page.screenshot({path:'docs/screenshots/inspector.png',fullPage:true})
 await page.getByRole('tab',{name:'Проверка серии',exact:true}).click()
 await page.getByText('Серия прошла техническую проверку.',{exact:true}).waitFor()
 await page.waitForFunction(()=>{const images=[...document.querySelectorAll('[aria-label="Просмотр серии"] img')];return images.length===4&&images.every(img=>img.complete&&img.naturalWidth>0)})
 await page.waitForFunction(()=>document.getAnimations().every(a=>a.playState!=='running'))
 await page.screenshot({path:'docs/screenshots/review.png',fullPage:true})
 await page.getByRole('tab',{name:'Бриф и бренд',exact:true}).click()
 await page.waitForFunction(()=>document.getAnimations().every(a=>a.playState!=='running'))
 await page.screenshot({path:'docs/screenshots/brand.png',fullPage:true})
 await page.getByRole('tab',{name:'Дизайн',exact:true}).click()
 await page.setViewportSize({width:390,height:1100})
 await page.evaluate(()=>window.scrollTo(0,0))
 await page.waitForFunction(()=>document.getAnimations().every(a=>a.playState!=='running'))
 await page.screenshot({path:'docs/screenshots/mobile.png'})
 await page.setViewportSize({width:1600,height:1100})
 await page.getByRole('link',{name:'Диалог',exact:true}).click()
 const clear=page.getByRole('button',{name:'Убрать результат',exact:true})
 if(await clear.count())await clear.click()
 await page.getByLabel('Действие',{exact:true}).selectOption('edit')
 await page.getByLabel('Контекст',{exact:true}).selectOption('slide')
 await page.getByRole('button',{name:/^Настройки/}).first().click()
 const model=await page.locator('#model option').evaluateAll(options=>options.find(option=>option.value&&!/AI|ИИ|bot/i.test(option.textContent))?.value)
 if(model)await page.locator('#model').selectOption(model)
 await page.getByRole('button',{name:/^Настройки/}).first().click()
 await page.route('**/studio-api/complete',route=>{
  const slide=route.request().postDataJSON().context.slides[0]
  return route.fulfill({json:{text:JSON.stringify({summary:'Обновить заголовок',operations:[{op:'update_layer',slideId:slide.id,layerId:slide.layers.find(layer=>layer.role==='heading').id,patch:{text:'Новые ритуалы'}}]})}})
 })
 await page.getByLabel('Запрос',{exact:true}).fill('Замени заголовок текущего слайда на «Новые ритуалы». Остальное сохрани.')
 await page.getByRole('button',{name:'Отправить запрос',exact:true}).click()
 await page.getByRole('button',{name:'Применить изменения',exact:true}).waitFor()
 await page.waitForFunction(()=>Array.from(document.querySelectorAll('img')).some(img=>img.alt==='Новые ритуалы'&&img.complete&&img.naturalWidth>0))
 await page.waitForFunction(()=>document.getAnimations().every(a=>a.playState!=='running'))
 await page.screenshot({path:'docs/screenshots/dialog.png',fullPage:true})
 await clear.click()
 await page.unroute('**/studio-api/complete')
 return {screenshots:6,slides:4,previewOnly:true}
}
