// oxlint-disable-next-line no-unused-expressions -- Evaluated by the browser CLI.
async (page) => {
  await page.goto('http://localhost:3080/')
  await page.getByRole('heading', { name: 'Редактор слайдов', exact: true }).waitFor()
  while (await page.getByRole('button', { name: /^Открыть слайд/ }).count() > 6) {
    await page.getByRole('button', { name: /^Открыть слайд/ }).last().click()
    await page.getByRole('button', { name: 'Удалить слайд', exact: true }).click()
  }
  await page.getByRole('button', { name: 'Открыть слайд 1', exact: true }).click()
  await page.getByRole('button', { name: 'Сгенерированное фото', exact: true }).click()
  await page.getByLabel('Высота слоя', { exact: true }).fill('650')
  await page.getByLabel('X', { exact: true }).fill('520')
  await page.getByLabel('Y', { exact: true }).fill('470')
  await page.getByRole('button', { name: 'Заголовок', exact: true }).click()
  await page.getByLabel('Текст слоя', { exact: true }).fill('Кофе в кадре.')
  await page.getByLabel('Текст слоя', { exact: true }).fill('Кофе в кадре')
  await page.getByLabel('Размер шрифта', { exact: true }).fill('68')
  await page.getByRole('button', { name: 'Основной текст', exact: true }).click()
  await page.getByLabel('Текст слоя', { exact: true }).fill('Поставьте чашку у окна.\n\nИспользуйте мягкий боковой свет.\n\nУберите лишние предметы из кадра.')
  await page.getByLabel('Ширина слоя', { exact: true }).fill('360')
  await page.getByLabel('Высота слоя', { exact: true }).fill('650')
  await page.getByLabel('Y', { exact: true }).fill('470')
  await page.getByLabel('Размер шрифта', { exact: true }).fill('38')
  await page.getByRole('button', { name: 'Подогнать текст', exact: true }).click()
  await page.getByLabel('Название группы', { exact: true }).fill('Кофе: первый кадр')
  await page.getByLabel('Тематика', { exact: true }).fill('Предметная фотография кофе')
  await page.getByLabel('Стилизация', { exact: true }).fill('Белый фон, крупная типографика, мягкий дневной свет и естественная предметная фотография')
  await page.getByRole('button', { name: 'Сгенерированное фото', exact: true }).click()
  await page.evaluate(() => scrollTo(0, 0))
  await page.screenshot({ path: 'output/playwright/studio-editor.png', fullPage: true, animations: 'disabled' })
  const png = page.waitForEvent('download')
  await page.getByRole('button', { name: 'PNG', exact: true }).click()
  await (await png).saveAs('output/playwright/studio-demo-slide.png')
  const json = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Сохранить JSON', exact: true }).click()
  await (await json).saveAs('output/playwright/studio-demo-project.json')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('region', { name: 'Холст слайда' }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'output/playwright/studio-mobile.png', fullPage: false })
  await page.setViewportSize({ width: 1600, height: 1100 })
  await page.evaluate(() => scrollTo(0, 0))
  return { prepared: ['Editable demo project', 'Desktop screenshot', 'Mobile screenshot', 'Exported demo PNG'] }
}
